apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coralberryfairy
    app.kubernetes.io/instance: coralberryfairy
    app.kubernetes.io/name: coralberryfairy
    deployment: coralberryfairy
  name: coralberryfairy
  namespace: coralberryfairy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: coralberryfairy
      app.kubernetes.io/instance: coralberryfairy
      app.kubernetes.io/name: coralberryfairy
      deployment: coralberryfairy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: coralberryfairy
        app.kubernetes.io/instance: coralberryfairy
        app.kubernetes.io/name: coralberryfairy
        deployment: coralberryfairy
    spec:
      containers:
      - name: coralberryfairy
        envFrom:
        - secretRef:
            name: cloud-zookeeper
        - secretRef:
            name: cloud-solr
        - secretRef:
            name: cloud-database
        - secretRef:
            name: cloud-auth
        - secretRef:
            name: cloud-context-broker
        - secretRef:
            name: cloud-site
        - secretRef:
            name: cloud-font-awesome
        - secretRef:
            name: cloud-extra
        image: quay.io/computateorg/coralberryfairy:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 10
        ports:
        - containerPort: 10240
          name: http
          protocol: TCP
        - containerPort: 10241
          name: cluster
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 750m
            ephemeral-storage: 1Gi
            memory: 768Mi
          requests:
            cpu: 750m
            ephemeral-storage: 1Gi
            memory: 768Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
