apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-pguser-coralberryfairy
  namespace: coralberryfairy
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: postgres-pguser-coralberryfairy
  dataFrom:
    - extract:
        key: coralberryfairy/kv/postgres-pguser-coralberryfairy
